---

# Kudos to: https://www.srijn.net/install-docker-and-docker-compose-using-ansible/

- name: Check current docker-compose version
  command: /usr/libexec/docker/cli-plugins/docker-compose --version
  register: docker_compose_vsn
  changed_when: false
  failed_when: false
  check_mode: no

- name: Write current version to local variable
  set_fact:
    docker_compose_current_version: "{{ docker_compose_vsn.stdout | regex_search('(\\d+(\\.\\d+)+)') }}"
  when:
    - docker_compose_vsn.stdout | length > 0

- name: Write default version 0 to local variable
  set_fact:
    docker_compose_current_version: "0"
  when:
    - docker_compose_vsn.stdout | length == 0

- name: "Target version for docker-compose"
  debug:
    var: docker_compose_version

- name: "Current version of docker-compose"
  debug:
    var: docker_compose_current_version

- name: "Install or upgrade docker-compose"
  get_url:
    url: "{{ docker_compose_url }}"
    dest: /usr/libexec/docker/cli-plugins/docker-compose
    mode: 'a+x'
    force: yes
  when:
    - docker_compose_current_version is version(docker_compose_version, '<')
